#see https://www.topaz.sh/docs/deployment/docker-compose for instructions
version: "3.5"
services:
  topaz:
    command:
      - run
      - --config-file
      - /config/local.yaml
    container_name: topaz
    environment:
      - TOPAZ_POLICIES_DIR=/policies
      - TOPAZ_CERTS_DIR=/certs
      - TOPAZ_DB_DIR=/db
    image: ghcr.io/aserto-dev/topaz:latest
    ports:
      - 8080:8080 # console http
      - 8081:8081 # console grpc
      - 8282:8282 # authorizer grpc
      - 8383:8383 # authoirzer http
      - 9292:9292 # directory grpc
      - 9393:9393 # directory http
      - 9494:9494 # healthcheck
      - 9696:9696 # metrics
    networks:
      - my-network
    volumes:
      - ./config:/config
      - ./policies:/policies
      - ./certs:/certs
      - ./db:/db
      - ./data:/data
  app:
    build: .       # Build the Go app from a Dockerfile in the current directory
    ports:
      - 8888:8888  # Expose port 8888 for the Go app
    depends_on:
      - topaz # Add topaz as a dependency
    networks:
      - my-network
    environment:
      - TOPAZ_IS_URL=https://topaz:8383/api/v2/authz/is # expose the authorizer as a url for the applicatio code to call
networks:
  my-network:
    driver: bridge
    name: my-network
